#!/bin/bash
dpkg-deb --build pythonshit/ pythonshit.deb
rm -r dcNotifyTg/etc/dcNotifyTg/__pycache__
dpkg-deb --build dcNotifyTg/ dcNotifyTgPRIV.deb

mv dcNotifyTg/etc/dcNotifyTg/dcTgData.db dcTgData.db
mv dcNotifyTg/etc/dcNotifyTg/config.dev.json config.dev.json
mv dcNotifyTg/etc/dcNotifyTg/config.json config.json
mv dcNotifyTg/etc/dcNotifyTg/config.json.template dcNotifyTg/etc/dcNotifyTg/config.json

dpkg-deb --build dcNotifyTg/ dcNotifyTg.deb

mv dcNotifyTg/etc/dcNotifyTg/config.json dcNotifyTg/etc/dcNotifyTg/config.json.template
mv config.json dcNotifyTg/etc/dcNotifyTg/config.json
mv config.dev.json dcNotifyTg/etc/dcNotifyTg/config.dev.json
mv dcTgData.db dcNotifyTg/etc/dcNotifyTg/dcTgData.db