#!/usr/bin/env python3
from matplotlib.dates import DAYS_PER_MONTH
import requests
import time
import json
import os
import sys
import datetime
from systemd.journal import JournalHandler
from sqlalchemy import create_engine, MetaData, Table, Column, Integer, String, DateTime, Boolean
from sqlalchemy.sql import func

#import numpy as np
import matplotlib.pyplot as plt
import matplotlib.dates as dates
import numpy as np


engine = create_engine('sqlite:///dcdata.db')
meta = MetaData()
conn = engine.connect()

# dcOn = Table(
# 'dcOn', meta,
# Column('timestamp', DateTime(timezone=True)),
# Column('username', String),
# Column('status', String),
# Column('channel_id', String),
# Column('deaf', Boolean),
# Column('mute', Boolean),
# Column('game',String)
# )
# meta.create_all(engine)

#states=list(conn.execute("SELECT DISTINCT status FROM dcOn"))
#states=[x[0] for x in states]
states=["idle","dnd"]
#states=list()

users = sys.argv[1::]
print(users)

def per_day():
    fig = plt.figure()
    ax1 = fig.add_subplot(2,1,1)
    days=list(conn.execute("SELECT DISTINCT date(timestamp) FROm dcOn ORDER BY date(timestamp)"))
    for user in users:
        datax=list()
        datay=list()
        for day in [x[0] for x in days]:
            res=list(conn.execute(f'SELECT COUNT(*) FROM dcOn WHERE username = "{user}" AND date(timestamp)="{day}"'))
            y,m,d=day.split("-")
            t=datetime.datetime(year=int(y),month=int(m),day=int(d))
            datax+=[t]
            datay+=res[0]
        datax = dates.date2num(datax)
        ax1.plot(datax,datay,label=user,linewidth=1)

        for status in states:
            datax=list()
            datay=list()
            for day in [x[0] for x in days]:
                res=list(conn.execute(f'SELECT COUNT(*) FROM dcOn WHERE username = "{user}" AND date(timestamp)="{day}" AND status="{status}"'))
                y,m,d=day.split("-")
                t=datetime.datetime(year=int(y),month=int(m),day=int(d))
                datax+=[t]
                datay+=res[0]
            datax = dates.date2num(datax)
            ax1.plot(datax,datay,label=f"{user}:{status}",linewidth=1)
    
    plt.xlabel("Day")
    plt.ylabel("Minutes online")
    plt.xticks([datetime.datetime(year=int(t[0]),month=int(t[1]),day=int(t[2])) for t in [(days[i][0].split("-")) for i in range(0,len(days))]])
    plt.yticks([x for x in range(0,int(24*60/5),int(60/5))],[5*x for x in range(0,int(24*60/5),int(60/5))])
    myFmt = dates.DateFormatter('%Y-%m-%d')
    plt.gca().xaxis.set_major_formatter(myFmt)
    plt.legend(bbox_to_anchor=(1,1), loc="upper left")
    plt.title(label="Total per day per user")
    plt.show()

def per_weekday():
    fig = plt.figure()
    ax1 = fig.add_subplot(2,1,1)
    days=list(conn.execute("SELECT DISTINCT strftime('%w',timestamp) FROm dcOn ORDER BY strftime('%w',timestamp)"))
    days=[int(x[0]) for x in days]
    datax=list()
    for user in users:
        datax=list()
        datay=list()
        for day in days:
            res=list(conn.execute(f'SELECT COUNT(*) FROM dcOn WHERE username = "{user}" AND strftime("%w",timestamp)="{day}"'))
            datax+=[day]
            datay+=res[0]
        ax1.plot(datax,datay,label=user,linewidth=1)

        for status in states:
            datax=list()
            datay=list()
            for day in days:
                res=list(conn.execute(f'SELECT COUNT(*) FROM dcOn WHERE username = "{user}" AND strftime("%w",timestamp)="{day}" AND status="{status}"'))
                datax+=[day]
                datay+=res[0]
            ax1.plot(datax,datay,label=f"{user}:{status}",linewidth=1)
    
    xticks=["So","Mo","Di","Mi","Do","Fr","Sa"]
    plt.xticks([x for x in range(0,7)], [xticks[x] for x in range(0,7)])
    plt.xlabel("Weekday")
    plt.yticks([x for x in range(0,int(24*60/5),int(60/5))],[5*x for x in range(0,int(24*60/5),int(60/5))])
    plt.ylabel("Minutes online")
    plt.legend(bbox_to_anchor=(1,1), loc="upper left")
    plt.title("Total per weekday per user")
    plt.show()

def per_time():
    fig = plt.figure()
    ax1 = fig.add_subplot(2,1,1)
    times=list(conn.execute("SELECT DISTINCT time(timestamp) FROM dcOn ORDER BY time(timestamp)"))
    for user in users:
        datax=list()
        datay=list()
        for time in [x[0] for x in times]:
            res=list(conn.execute(f'SELECT COUNT(*) FROM dcOn WHERE username = "{user}" AND time(timestamp)="{time}"'))
            h,m,_=time.split(":")
            t=datetime.datetime(year=1970,month=1,day=1,hour=int(h),minute=int(m))
            datax+=[t]
            datay+=res[0]
        datax = dates.date2num(datax)
        ax1.plot(datax,datay,label=user,linewidth=1)

        for status in states:
            datax=list()
            datay=list()
            for time in [x[0] for x in times]:
                res=list(conn.execute(f'SELECT COUNT(*) FROM dcOn WHERE username = "{user}" AND time(timestamp)="{time}" AND status="{status}"'))
                h,m,_=time.split(":")
                t=datetime.datetime(year=1970,month=1,day=1,hour=int(h),minute=int(m))
                datax+=[t]
                datay+=res[0]
            datax = dates.date2num(datax)
            ax1.plot(datax,datay,label=f"{user}:{status}",linewidth=1)
    
    plt.xlabel("Time")
    plt.ylabel("Hits Online at this time")
    plt.xticks([datetime.datetime(year=1970,month=1,day=1,hour=h)for h in range (0,24)])
    myFmt = dates.DateFormatter('%H:%M')
    plt.gca().xaxis.set_major_formatter(myFmt)
    plt.legend(bbox_to_anchor=(1,1), loc="upper left")
    plt.title("Total per time per user")
    plt.show()

def per_week():
    fig = plt.figure()
    ax1 = fig.add_subplot(2,1,1)

    #weeks=list(conn.execute("SELECT DISTINCT strftime('%W',timestamp) FROm dcOn ORDER BY strftime('%W',timestamp)"))
    #weeks=[int(x[0]) for x in weeks]
    wdays=list(conn.execute("SELECT DISTINCT strftime('%w',timestamp) FROm dcOn ORDER BY strftime('%w',timestamp)"))
    wdays=[int(x[0]) for x in wdays]
    # days=list(conn.execute("SELECT DISTINCT date(timestamp) FROm dcOn ORDER BY date(timestamp)"))
    # days=[x[0] for x in days]
    times=list(conn.execute("SELECT DISTINCT time(timestamp) FROM dcOn ORDER BY time(timestamp)"))
    times=[x[0] for x in times]

    for user in users:
        datax=list()
        datay=list()
        for day in wdays:
            for time in times:
                res=list(conn.execute(f'SELECT COUNT(*) FROM dcOn WHERE username = "{user}" AND strftime("%w",timestamp)="{day}" AND time(timestamp)="{time}"'))
                h,m,_=time.split(":")
                t=datetime.datetime(year=1970,month=1,day=day+4,hour=int(h),minute=int(m))
                datax+=[t]
                datay+=res[0]
        ax1.plot(datax,datay,label=user,linewidth=1)

        for status in states:
            datax=list()
            datay=list()
            for day in wdays:
                for time in times:
                    res=list(conn.execute(f'SELECT COUNT(*) FROM dcOn WHERE username = "{user}" AND strftime("%w",timestamp)="{day}" AND time(timestamp)="{time}" AND status="{status}"'))
                    h,m,_=time.split(":")
                    t=datetime.datetime(year=1970,month=1,day=day+4,hour=int(h),minute=int(m))
                    datax+=[t]
                    datay+=res[0]
            ax1.plot(datax,datay,label=f"{user}:{status}",linewidth=1)
    
    plt.xlabel("Weekday:Time")
    plt.ylabel("Hits Online at this time")
    plt.xticks([datetime.datetime(year=1970,month=1,day=day+4,hour=3*h)for h in range (0,24//3) for day in range(0,7)])
    myFmt = dates.DateFormatter('%H')
    plt.gca().xaxis.set_major_formatter(myFmt)
    plt.legend(bbox_to_anchor=(1,1), loc="upper left")
    plt.title("Total per time in a week per user")
    plt.show()

def total():
    fig = plt.figure()
    ax1 = fig.add_subplot(2,1,1)
    data=list()
    bar_label=list()
    y_pos=[0]
    maxi=0
    for user in users:
        data+=list(conn.execute(f'SELECT COUNT(*) FROM dcOn WHERE username = "{user}"'))[0]
        bar_label+=[f"{user}: Total"]
        for status in states:
            data+=list(conn.execute(f'SELECT COUNT(*) FROM dcOn WHERE username = "{user}" AND status="{status}"'))[0]
            bar_label+=[f"{user}: {status}"]
        data+=list(conn.execute(f'SELECT COUNT(*) FROM dcOn WHERE username = "{user}" AND mute = 1'))[0]
        bar_label+=[f"{user}: muted"]
        data+=list(conn.execute(f'SELECT COUNT(*) FROM dcOn WHERE username = "{user}" AND channel_id IS NOT NULL AND mute != 1'))[0]
        bar_label+=[f"{user}: channel"]

        temp=0
        times=list(conn.execute(f'SELECT timestamp FROM dcOn WHERE username = "{user}" AND channel_id IS NOT NULL AND channel_id != "696401199120777247"'))
        times=[x[0] for x in times]
        for time in times:
            res=list(conn.execute(f'SELECT COUNT(*) FROM dcOn WHERE timestamp = "{time}" AND channel_id IS NOT NULL AND channel_id != "696401199120777247"'))[0]
            if res[0]==1:
                temp+=1
        data+=[temp]
        bar_label+=[f"{user}: lonley"]

        y_pos = np.arange(len(bar_label))
        maxi=max(data)
        ax1.barh(y_pos, data, label=user)
    plt.ylabel("Category")
    plt.xlabel("Hits")
    #plt.xticks([datetime.datetime(year=int(t[0]),month=int(t[1]),day=int(t[2])) for t in [(days[i][0].split("-")) for i in range(0,len(days))]])
    #plt.xticks([x for x in range(0,int(24*60/5),int(60/5))],[5*x for x in range(0,maxi,maxi)])
    plt.yticks(y_pos,bar_label)
    plt.legend(bbox_to_anchor=(1,1), loc="upper left")
    plt.title(label="Total")
    plt.show()

def per_day_median():
    days=list(conn.execute("SELECT DISTINCT date(timestamp) FROm dcOn ORDER BY date(timestamp)"))
    for user in users:
        fig = plt.figure()
        ax1 = fig.add_subplot(2,1,1)
        data=list()
        for day in [x[0] for x in days]:
            res=list(conn.execute(f'SELECT COUNT(*) FROM dcOn WHERE username = "{user}" AND date(timestamp)="{day}"'))
            data+=res[0]
        data=[x*5/60 for x in data if x!= 0]
        ax1.boxplot(data, vert=0)
        plt.xlabel("Hours online")
        plt.legend(bbox_to_anchor=(1,1), loc="upper left")
        plt.title(label=f"Total Hours from {user}")
        plt.show()
    

per_day()
per_weekday()
per_time()
total()
per_day_median()