#!/usr/bin/env python3
from matplotlib.dates import DAYS_PER_MONTH
import requests
import time
import json
import os
import sys
import datetime
from systemd.journal import JournalHandler
from sqlalchemy import create_engine, MetaData, Table, Column, Integer, String, DateTime, Boolean
from sqlalchemy.sql import func

#import numpy as np
import matplotlib.pyplot as plt
import matplotlib.dates as dates


engine = create_engine('sqlite:///dcdata.db')
meta = MetaData()
conn = engine.connect()

dcOn = Table(
'dcOn', meta,
Column('timestamp', DateTime(timezone=True)),
Column('username', String),
Column('status', String),
Column('channel_id', String),
Column('deaf', Boolean),
Column('mute', Boolean),
)
meta.create_all(engine)

states=list(conn.execute("SELECT DISTINCT status FROM dcOn"))

users = sys.argv[1::]
print(users)

def total_per_day_per_user():
    fig = plt.figure()
    ax1 = fig.add_subplot(2,1,1)
    days=list(conn.execute("SELECT DISTINCT date(timestamp) FROm dcOn ORDER BY date(timestamp)"))
    for user in users:
        datax=list()
        datay=list()
        for day in [x[0] for x in days]:
            res=list(conn.execute(f'SELECT COUNT(*) FROM dcOn WHERE username = "{user}" AND date(timestamp)="{day}"'))
            y,m,d=day.split("-")
            t=datetime.datetime(year=int(y),month=int(m),day=int(d))
            datax+=[t]
            datay+=res[0]
        datax = dates.date2num(datax)
        ax1.plot(datax,datay,label=user,linewidth=1)
    plt.xlabel("Day")
    plt.ylabel("Minutes online")
    plt.xticks([datetime.datetime(year=int(t[0]),month=int(t[1]),day=int(t[2])) for t in [(days[i][0].split("-")) for i in range(0,len(days))]])
    plt.yticks([x for x in range(0,int(24*60/5),int(60/5))],[5*x for x in range(0,int(24*60/5),int(60/5))])
    myFmt = dates.DateFormatter('%Y-%m-%d')
    plt.gca().xaxis.set_major_formatter(myFmt)
    plt.legend(bbox_to_anchor=(1,1), loc="upper left")
    plt.title(label="Total per day per user")
    plt.show()

def total_per_day_per_user_status():
    fig = plt.figure()
    ax1 = fig.add_subplot(2,1,1)
    days=list(conn.execute("SELECT DISTINCT date(timestamp) FROm dcOn ORDER BY date(timestamp)"))
    for user in users:
        datax=list()
        datay=list()
        for day in [x[0] for x in days]:
            res=list(conn.execute(f'SELECT COUNT(*) FROM dcOn WHERE username = "{user}" AND date(timestamp)="{day}"'))
            y,m,d=day.split("-")
            t=datetime.datetime(year=int(y),month=int(m),day=int(d))
            datax+=[t]
            datay+=res[0]
        datax = dates.date2num(datax)
        ax1.plot(datax,datay,label=user,linewidth=1)

        for status in [x[0] for x in states]:
            datax=list()
            datay=list()
            for day in [x[0] for x in days]:
                res=list(conn.execute(f'SELECT COUNT(*) FROM dcOn WHERE username = "{user}" AND date(timestamp)="{day}" AND status="{status}"'))
                y,m,d=day.split("-")
                t=datetime.datetime(year=int(y),month=int(m),day=int(d))
                datax+=[t]
                datay+=res[0]
            datax = dates.date2num(datax)
            ax1.plot(datax,datay,label=f"{user}:{status}",linewidth=1)
    
    plt.xlabel("Day")
    plt.ylabel("Minutes online")
    plt.xticks([datetime.datetime(year=int(t[0]),month=int(t[1]),day=int(t[2])) for t in [(days[i][0].split("-")) for i in range(0,len(days))]])
    plt.yticks([x for x in range(0,int(24*60/5),int(60/5))],[5*x for x in range(0,int(24*60/5),int(60/5))])
    myFmt = dates.DateFormatter('%Y-%m-%d')
    plt.gca().xaxis.set_major_formatter(myFmt)
    plt.legend(bbox_to_anchor=(1,1), loc="upper left")
    plt.title(label="Total per day per user")
    plt.show()

def total_per_weekday_per_user():
    fig = plt.figure()
    ax1 = fig.add_subplot(2,1,1)
    days=list(conn.execute("SELECT DISTINCT strftime('%w',timestamp) FROm dcOn ORDER BY strftime('%w',timestamp)"))
    datax=list()
    for user in users:
        datax=list()
        datay=list()
        for day in [x[0] for x in days]:
            res=list(conn.execute(f'SELECT COUNT(*) FROM dcOn WHERE username = "{user}" AND strftime("%w",timestamp)="{day}"'))
            datax+=[day]
            datay+=res[0]
        ax1.plot(datax,datay,label=user,linewidth=1)
    xticks=["So","Mo","Di","Mi","Do","Fr","Sa"]
    plt.xticks([x for x in range(0,7)], [xticks[x] for x in range(0,7)])
    plt.xlabel("Weekday")
    plt.yticks([x for x in range(0,int(24*60/5),int(60/5))],[5*x for x in range(0,int(24*60/5),int(60/5))])
    plt.ylabel("Minutes online")
    plt.legend(bbox_to_anchor=(1,1), loc="upper left")
    plt.title("Total per weekday per user")
    plt.show()

def total_per_weekday_per_user_per_status():
    fig = plt.figure()
    ax1 = fig.add_subplot(2,1,1)
    days=list(conn.execute("SELECT DISTINCT strftime('%w',timestamp) FROm dcOn ORDER BY strftime('%w',timestamp)"))
    days=[int(x[0]) for x in days]
    datax=list()
    for user in users:
        datax=list()
        datay=list()
        for day in days:
            res=list(conn.execute(f'SELECT COUNT(*) FROM dcOn WHERE username = "{user}" AND strftime("%w",timestamp)="{day}"'))
            datax+=[day]
            datay+=res[0]
        ax1.plot(datax,datay,label=user,linewidth=1)

        for status in [x[0] for x in states]:
            datax=list()
            datay=list()
            for day in days:
                res=list(conn.execute(f'SELECT COUNT(*) FROM dcOn WHERE username = "{user}" AND strftime("%w",timestamp)="{day}" AND status="{status}"'))
                datax+=[day]
                datay+=res[0]
            ax1.plot(datax,datay,label=f"{user}:{status}",linewidth=1)
    
    xticks=["So","Mo","Di","Mi","Do","Fr","Sa"]
    plt.xticks([x for x in range(0,7)], [xticks[x] for x in range(0,7)])
    plt.xlabel("Weekday")
    plt.yticks([x for x in range(0,int(24*60/5),int(60/5))],[5*x for x in range(0,int(24*60/5),int(60/5))])
    plt.ylabel("Minutes online")
    plt.legend(bbox_to_anchor=(1,1), loc="upper left")
    plt.title("Total per weekday per user")
    plt.show()

def total_per_user_per_time():
    fig = plt.figure()
    ax1 = fig.add_subplot(2,1,1)
    times=list(conn.execute("SELECT DISTINCT time(timestamp) FROM dcOn ORDER BY time(timestamp)"))
    for user in users:
        datax=list()
        datay=list()
        for time in [x[0] for x in times]:
            res=list(conn.execute(f'SELECT COUNT(*) FROM dcOn WHERE username = "{user}" AND time(timestamp)="{time}"'))
            h,m,_=time.split(":")
            t=datetime.datetime(year=1970,month=1,day=1,hour=int(h),minute=int(m))
            datax+=[t]
            datay+=res[0]
        datax = dates.date2num(datax)
        ax1.plot(datax,datay,label=user,linewidth=1)
    plt.xlabel("Time")
    plt.ylabel("Hits Online at this time")
    plt.xticks([datetime.datetime(year=1970,month=1,day=1,hour=h)for h in range (0,24)])
    myFmt = dates.DateFormatter('%H:%M')
    plt.gca().xaxis.set_major_formatter(myFmt)
    plt.legend(bbox_to_anchor=(1,1), loc="upper left")
    plt.title("Total per time per user")
    plt.show()

def total_per_user_per_time_per_status():
    fig = plt.figure()
    ax1 = fig.add_subplot(2,1,1)
    times=list(conn.execute("SELECT DISTINCT time(timestamp) FROM dcOn ORDER BY time(timestamp)"))
    for user in users:
        datax=list()
        datay=list()
        for time in [x[0] for x in times]:
            res=list(conn.execute(f'SELECT COUNT(*) FROM dcOn WHERE username = "{user}" AND time(timestamp)="{time}"'))
            h,m,_=time.split(":")
            t=datetime.datetime(year=1970,month=1,day=1,hour=int(h),minute=int(m))
            datax+=[t]
            datay+=res[0]
        datax = dates.date2num(datax)
        ax1.plot(datax,datay,label=user,linewidth=1)

        for status in [x[0] for x in states]:
            datax=list()
            datay=list()
            for time in [x[0] for x in times]:
                res=list(conn.execute(f'SELECT COUNT(*) FROM dcOn WHERE username = "{user}" AND time(timestamp)="{time}" AND status="{status}"'))
                h,m,_=time.split(":")
                t=datetime.datetime(year=1970,month=1,day=1,hour=int(h),minute=int(m))
                datax+=[t]
                datay+=res[0]
            datax = dates.date2num(datax)
            ax1.plot(datax,datay,label=f"{user}:{status}",linewidth=1)
    
    plt.xlabel("Time")
    plt.ylabel("Hits Online at this time")
    plt.xticks([datetime.datetime(year=1970,month=1,day=1,hour=h)for h in range (0,24)])
    myFmt = dates.DateFormatter('%H:%M')
    plt.gca().xaxis.set_major_formatter(myFmt)
    plt.legend(bbox_to_anchor=(1,1), loc="upper left")
    plt.title("Total per time per user")
    plt.show()

def week_per_user_per_status():
    fig = plt.figure()
    ax1 = fig.add_subplot(2,1,1)

    states=[("idle",),("dnd",)]

    #weeks=list(conn.execute("SELECT DISTINCT strftime('%W',timestamp) FROm dcOn ORDER BY strftime('%W',timestamp)"))
    #weeks=[int(x[0]) for x in weeks]
    wdays=list(conn.execute("SELECT DISTINCT strftime('%w',timestamp) FROm dcOn ORDER BY strftime('%w',timestamp)"))
    wdays=[int(x[0]) for x in wdays]
    # days=list(conn.execute("SELECT DISTINCT date(timestamp) FROm dcOn ORDER BY date(timestamp)"))
    # days=[x[0] for x in days]
    times=list(conn.execute("SELECT DISTINCT time(timestamp) FROM dcOn ORDER BY time(timestamp)"))
    times=[x[0] for x in times]

    for user in users:
        datax=list()
        datay=list()
        for day in wdays:
            for time in times:
                res=list(conn.execute(f'SELECT COUNT(*) FROM dcOn WHERE username = "{user}" AND strftime("%w",timestamp)="{day}" AND time(timestamp)="{time}"'))
                h,m,_=time.split(":")
                t=datetime.datetime(year=1970,month=1,day=day+4,hour=int(h),minute=int(m))
                datax+=[t]
                datay+=res[0]
        ax1.plot(datax,datay,label=user,linewidth=1)

        for status in [x[0] for x in states]:
            datax=list()
            datay=list()
            for day in wdays:
                for time in times:
                    res=list(conn.execute(f'SELECT COUNT(*) FROM dcOn WHERE username = "{user}" AND strftime("%w",timestamp)="{day}" AND time(timestamp)="{time}" AND status="{status}"'))
                    h,m,_=time.split(":")
                    t=datetime.datetime(year=1970,month=1,day=day+4,hour=int(h),minute=int(m))
                    datax+=[t]
                    datay+=res[0]
            ax1.plot(datax,datay,label=f"{user}:{status}",linewidth=1)
    
    plt.xlabel("Weekday:Time")
    plt.ylabel("Hits Online at this time")
    plt.xticks([datetime.datetime(year=1970,month=1,day=day+4,hour=3*h)for h in range (0,24//3) for day in range(0,7)])
    myFmt = dates.DateFormatter('%H')
    plt.gca().xaxis.set_major_formatter(myFmt)
    plt.legend(bbox_to_anchor=(1,1), loc="upper left")
    plt.title("Total per time in a week per user")
    plt.show()

def total():
    fig = plt.figure()
    ax1 = fig.add_subplot(2,1,1)
    days=list(conn.execute("SELECT DISTINCT timestamp FROm dcOn ORDER BY timestamp"))
    for user in users:
        datax=list()
        datay=list()
        for day in [x[0] for x in days]:
            res=list(conn.execute(f'SELECT COUNT(*) FROM dcOn WHERE username = "{user}" AND timestamp="{day}"'))
            datax+=[day]
            datay+=res[0]
        datax = dates.date2num(datax)
        ax1.plot(datax,datay,label=user,linewidth=1)
    plt.xlabel("Day")
    plt.ylabel("Minutes online")
    #plt.xticks([datetime.datetime(year=int(t[0]),month=int(t[1]),day=int(t[2])) for t in [(days[i][0].split("-")) for i in range(0,len(days))]])
    #plt.yticks([x for x in range(0,int(24*60/5),int(60/5))],[5*x for x in range(0,int(24*60/5),int(60/5))])
    myFmt = dates.DateFormatter('%Y-%m-%d')
    plt.gca().xaxis.set_major_formatter(myFmt)
    plt.legend(bbox_to_anchor=(1,1), loc="upper left")
    plt.title(label="Total per day per user")
    plt.show()

# total()
# total_per_day_per_user_status()
# total_per_weekday_per_user_per_status()
# total_per_user_per_time_per_status()
# week_per_user_per_status()

total_per_day_per_user()
total_per_weekday_per_user()
total_per_user_per_time()